### ISSUE TITLE
AttributeError on startup

### ISSUE THREAD

**Issue by dvs1** [SunyataZero/well-being-diary#3]
When trying `python3 well-being-diary.py`:

```python
Traceback (most recent call last):
  File "...central.py", line 148, in on_view_radio_button_toggled
    self.update_gui()
  File "...central.py", line 172, in update_gui
    self.add_bn_w3.setText(ADD_DIARY_BN_TEXT_STR)
AttributeError: 'CompositeCentralWidget' object has no attribute 'add_bn_w3'
```

**Comment by dvs1** [comment]
I confirm the fix.
