### ISSUE TITLE
crash when "Monthly question view" is selected

### ISSUE THREAD

**Issue by dvs1** [SunyataZero/well-being-diary#4]
When I press the "Monthly question view" radio button:

```python
Traceback (most recent call last):
  File "...central.py", line 149, in on_view_radio_button_toggled
    self.update_gui()
  File "...central.py", line 158, in update_gui
    assert wbd.wbd_global.active_question_id_it != wbd.wbd_global.NO_ACTIVE_QUESTION_INT
AssertionError
```

**Comment by SunyataZero** [comment]
@dvs1 Thank you for finding and reporting this, i've now done testing on the application and fixed a few other issues as well as this one

**Comment by dvs1** [comment]
I confirm the fix.
