### ISSUE TITLE
Crash when trying to delete a question

### ISSUE THREAD

**Issue by H4rryK4ne** [SunyataZero/well-being-diary#43]
When a question should be deleted and the name is confirmed the program crashes:

```
Traceback (most recent call last):
  File "<path>\well-being-diary\wbd\gui\window.py", line 199, in on_question_current_row_changed
    self.update_gui(EventSource.obs_current_row_changed)
  File "<path>\well-being-diary\wbd\gui\window.py", line 274, in update_gui
    self.central_widget_w3.update_gui()
  File "<path>\well-being-diary\wbd\gui\central.py", line 286, in update_gui
    self.diary_widget.update_gui()
  File "<path>\well-being-diary\wbd\gui\diary.py", line 176, in update_gui
    wbd.wbd_global.current_page_number_int
  File "<path>\well-being-diary\wbd\model.py", line 515, in get_all_for_question
    + " OFFSET " + str(i_page_number_int * wbd.wbd_global.diary_entries_per_page_int)
sqlite3.OperationalError: no such column: None
```

**Comment by SunyataZero** [comment]
Hi, and thank you for filing this issue, i am just now working on a major redesign of this prototype, i've been thinking about this for a long long time now! Would you be interested in being a "super-user" and give feedback and perhaps ideas for the application? You could join us here if you like: https://gitter.im/well-being-diary/Lobby

**Comment by SunyataZero** [comment]
Okay, this has now been fixed!
